/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type FB_CUSTOM_AUDIENCE = {
  [k: string]: unknown;
} & {
  accessToken: string;
  appSecret?: string;
  maxUserCount?: string;
  userSchema?: (
    | "EMAIL"
    | "PHONE"
    | "GEN"
    | "MADID"
    | "EXTERN_ID"
    | "DOBY"
    | "DOBM"
    | "DOBD"
    | "LN"
    | "FN"
    | "FI"
    | "CT"
    | "ST"
    | "ZIP"
    | "COUNTRY"
  )[];
  isHashRequired?: boolean;
  isRaw?: boolean;
  disableFormat?: boolean;
  type?:
    | "UNKNOWN"
    | "FILE_IMPORTED"
    | "EVENT_BASED"
    | "SEED_BASED"
    | "THIRD_PARTY_IMPORTED"
    | "COPY_PASTE"
    | "CONTACT_IMPORTER"
    | "HOUSEHOLD_AUDIENCE"
    | "NA";
  subType?:
    | "ANYTHING"
    | "NOTHING"
    | "HASHES"
    | "USER_IDS"
    | "HASHES_OR_USER_IDS"
    | "MOBILE_ADVERTISER_IDS"
    | "FB_EVENT_SIGNALS"
    | "EXTERNAL_IDS"
    | "MULTI_HASHES"
    | "TOKENS"
    | "EXTERNAL_IDS_MIX"
    | "WEB_PIXEL_HITS"
    | "MOBILE_APP_EVENTS"
    | "MOBILE_APP_COMBINATION_EVENTS"
    | "VIDEO_EVENTS"
    | "WEB_PIXEL_COMBINATION_EVENTS"
    | "IG_BUSINESS_EVENTS"
    | "MULTI_DATA_EVENTS"
    | "STORE_VISIT_EVENTS"
    | "INSTANT_ARTICLE_EVENTS"
    | "ENGAGEMENT_EVENT_USERS"
    | "FACEBOOK_WIFI_EVENTS"
    | "CUSTOM_AUDIENCE_USERS"
    | "S_EXPR"
    | "DYNAMIC_RULE"
    | "CONVERSION_PIXEL_HITS"
    | "APP_USERS"
    | "CAMPAIGN_CONVERSIONS"
    | "WEB_PIXEL_HITS_CUSTOM_AUDIENCE_USERS"
    | "MOBILE_APP_CUSTOM_AUDIENCE_USERS"
    | "VIDEO_EVENT_USERS"
    | "FB_PIXEL_HITS"
    | "IG_PROMOTED_POST"
    | "PLACE_VISITS"
    | "OFFLINE_EVENT_USERS"
    | "EXPANDED_AUDIENCE"
    | "SEED_LIST"
    | "PARTNER_CATEGORY_USERS"
    | "PAGE_SMART_AUDIENCE"
    | "MULTICOUNTRY_COMBINATION"
    | "PLATFORM_USERS"
    | "MULTI_EVENT_SOURCE"
    | "SMART_AUDIENCE"
    | "LOOKALIKE_PLATFORM"
    | "SIGNAL_SOURCE"
    | "MAIL_CHIMP_EMAIL_HASHES"
    | "CONSTANT_CONTACTS_EMAIL_HASHES"
    | "COPY_PASTE_EMAIL_HASHES"
    | "CONTACT_IMPORTER"
    | "DATA_FILE"
    | "NA";
  oneTrustCookieCategories?: {
    cloud?: {
      oneTrustCookieCategory?: string;
      [k: string]: unknown;
    }[];
    warehouse?: {
      oneTrustCookieCategory?: string;
      [k: string]: unknown;
    }[];
    shopify?: {
      oneTrustCookieCategory?: string;
      [k: string]: unknown;
    }[];
    [k: string]: unknown;
  };
  consentManagement?: {
    cloud?: {
      [k: string]: unknown;
    }[];
    warehouse?: {
      [k: string]: unknown;
    }[];
    shopify?: {
      [k: string]: unknown;
    }[];
    [k: string]: unknown;
  };
  connectionMode?: {
    shopify?: "cloud";
    cloud?: "cloud";
    warehouse?: "cloud";
    [k: string]: unknown;
  };
  ketchConsentPurposes?: {
    cloud?: {
      purpose?: string;
      [k: string]: unknown;
    }[];
    warehouse?: {
      purpose?: string;
      [k: string]: unknown;
    }[];
    shopify?: {
      purpose?: string;
      [k: string]: unknown;
    }[];
    [k: string]: unknown;
  };
  [k: string]: unknown;
};
