/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type SFTP = {
  [k: string]: unknown;
} & {
  host: string;
  port: string;
  username: string;
  authMethod: "passwordAuth" | "keyAuth";
  fileFormat: "json" | "csv";
  filePath: string;
  oneTrustCookieCategories?: {
    warehouse?: {
      oneTrustCookieCategory?: string;
      [k: string]: unknown;
    }[];
    [k: string]: unknown;
  };
  connectionMode?: {
    warehouse?: "cloud";
    [k: string]: unknown;
  };
  ketchConsentPurposes?: {
    warehouse?: {
      purpose?: string;
      [k: string]: unknown;
    }[];
    [k: string]: unknown;
  };
  [k: string]: unknown;
};
