/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type GOOGLEADS = {
  [k: string]: unknown;
} & {
  v2?: boolean;
  allowIdentify?: boolean;
  conversionID: string;
  eventMappingFromConfig?: {
    from?: string;
    to?:
      | "Lead"
      | "PageVisit"
      | "ViewCategory"
      | "Signup"
      | "WatchVideo"
      | "Checkout"
      | "Search"
      | "AddToCart"
      | "purchase"
      | "";
    [k: string]: unknown;
  }[];
  trackConversions?: boolean;
  trackDynamicRemarketing?: boolean;
  useNativeSDK?: {
    web?: boolean;
    [k: string]: unknown;
  };
  eventFilteringOption?: "disable" | "whitelistedEvents" | "blacklistedEvents";
  whitelistedEvents?: {
    eventName?: string;
    [k: string]: unknown;
  }[];
  blacklistedEvents?: {
    eventName?: string;
    [k: string]: unknown;
  }[];
  pageLoadConversions?: {
    conversionLabel?: string;
    name?: string;
    [k: string]: unknown;
  }[];
  defaultPageConversion?: string;
  clickEventConversions?: {
    conversionLabel?: string;
    name?: string;
    [k: string]: unknown;
  }[];
  sendPageView?: boolean;
  conversionLinker?: boolean;
  disableAdPersonalization?: boolean;
  enableConversionLabel?: boolean;
  allowEnhancedConversions?: boolean;
  oneTrustCookieCategories?: {
    web?: {
      oneTrustCookieCategory?: string;
      [k: string]: unknown;
    }[];
    [k: string]: unknown;
  };
  connectionMode?: {
    web?: "device";
    [k: string]: unknown;
  };
  consentManagement?: {
    web?: {
      [k: string]: unknown;
    }[];
    [k: string]: unknown;
  };
  ketchConsentPurposes?: {
    web?: {
      purpose?: string;
      [k: string]: unknown;
    }[];
    [k: string]: unknown;
  };
  [k: string]: unknown;
};
