/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface PODSIGHTS {
  pixelId: string;
  eventsToPodsightsEvents?: {
    from?: string;
    to?: "lead" | "product" | "addtocart" | "checkout" | "purchase" | "";
    [k: string]: unknown;
  }[];
  enableAliasCall?: boolean;
  eventFilteringOption?: "disable" | "whitelistedEvents" | "blacklistedEvents";
  whitelistedEvents?: {
    eventName?: string;
    [k: string]: unknown;
  }[];
  blacklistedEvents?: {
    eventName?: string;
    [k: string]: unknown;
  }[];
  useNativeSDK?: {
    web?: boolean;
    [k: string]: unknown;
  };
  oneTrustCookieCategories?: {
    web?: {
      oneTrustCookieCategory?: string;
      [k: string]: unknown;
    }[];
    [k: string]: unknown;
  };
  consentManagement?: {
    web?: {
      [k: string]: unknown;
    }[];
    [k: string]: unknown;
  };
  connectionMode?: {
    web?: "device";
    [k: string]: unknown;
  };
  ketchConsentPurposes?: {
    web?: {
      purpose?: string;
      [k: string]: unknown;
    }[];
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
