/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface SENTRY {
  dsn: string;
  environment?: string;
  customVersionProperty?: string;
  release?: string;
  serverName?: string;
  logger?: string;
  ignoreErrors?: {
    ignoreErrors?: string;
    [k: string]: unknown;
  }[];
  includePaths?: {
    includePaths?: string;
    [k: string]: unknown;
  }[];
  allowUrls?: {
    allowUrls?: string;
    [k: string]: unknown;
  }[];
  denyUrls?: {
    denyUrls?: string;
    [k: string]: unknown;
  }[];
  debugMode?: boolean;
  useNativeSDK?: {
    web?: boolean;
    [k: string]: unknown;
  };
  eventFilteringOption?: "disable" | "whitelistedEvents" | "blacklistedEvents";
  whitelistedEvents?: {
    eventName?: string;
    [k: string]: unknown;
  }[];
  blacklistedEvents?: {
    eventName?: string;
    [k: string]: unknown;
  }[];
  oneTrustCookieCategories?: {
    web?: {
      oneTrustCookieCategory?: string;
      [k: string]: unknown;
    }[];
    [k: string]: unknown;
  };
  consentManagement?: {
    web?: {
      [k: string]: unknown;
    }[];
    [k: string]: unknown;
  };
  connectionMode?: {
    web?: "device";
    [k: string]: unknown;
  };
  ketchConsentPurposes?: {
    web?: {
      purpose?: string;
      [k: string]: unknown;
    }[];
    [k: string]: unknown;
  };
}
