/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface THE_TRADE_DESK {
  audienceId?: string;
  advertiserId: string;
  advertiserSecretKey: string;
  ttlInDays?: string;
  dataServer: "apac" | "tokyo" | "usEastCoast" | "usWestCoast" | "ukEu" | "china";
  oneTrustCookieCategories?: {
    warehouse?: {
      oneTrustCookieCategory?: string;
      [k: string]: unknown;
    }[];
    [k: string]: unknown;
  };
  consentManagement?: {
    warehouse?: {
      [k: string]: unknown;
    }[];
    [k: string]: unknown;
  };
  connectionMode?: {
    warehouse?: "cloud";
    [k: string]: unknown;
  };
  ketchConsentPurposes?: {
    warehouse?: {
      purpose?: string;
      [k: string]: unknown;
    }[];
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
