/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface LYTICS_BULK_UPLOAD {
  lyticsAccountId: string;
  lyticsApiKey: string;
  lyticsStreamName?: string;
  timestampField?: string;
  streamTraitsMapping?: {
    rudderProperty?: string;
    lyticsProperty?: string;
    [k: string]: unknown;
  }[];
  oneTrustCookieCategories?: {
    warehouse?: {
      oneTrustCookieCategory?: string;
      [k: string]: unknown;
    }[];
    web?: {
      oneTrustCookieCategory?: string;
      [k: string]: unknown;
    }[];
    cloud?: {
      oneTrustCookieCategory?: string;
      [k: string]: unknown;
    }[];
    [k: string]: unknown;
  };
  connectionMode?: {
    cloud?: "cloud";
    warehouse?: "cloud";
    web?: "cloud";
    [k: string]: unknown;
  };
  ketchConsentPurposes?: {
    warehouse?: {
      purpose?: string;
      [k: string]: unknown;
    }[];
    web?: {
      purpose?: string;
      [k: string]: unknown;
    }[];
    cloud?: {
      purpose?: string;
      [k: string]: unknown;
    }[];
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
