# .github/workflows/create-hotfix-branch.yml

name: Create New Hotfix Branch

on:
  workflow_dispatch:
    inputs:
      hotfix_name:
        description: Hotfix branch name
        required: true

permissions:
  contents: read

jobs:
  validate-actor:
    uses: ./.github/workflows/validate-actor.yml
    with:
      team_names: 'integrations,data-management,sdk_team'
    secrets:
      RELEASE_PRIVATE_KEY: ${{ secrets.RELEASE_PRIVATE_KEY }}

  create-branch:
    name: Create New Branch
    runs-on: ubuntu-latest
    needs: validate-actor
    permissions:
      contents: write

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@bf7454d06d71f1098171f2acdf0cd4708d7b5920 # v2.20.0
        with:
          egress-policy: audit

      - name: Create Branch
        if: success()
        uses: peterjgrainger/action-create-branch@4b81ce657e255acd677cc6c55c9c763654be3aef # v4.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: 'hotfix/${{ github.event.inputs.hotfix_name }}'
