name: Deploy Configurations To Production DB

on:
  workflow_call:
    inputs:
      deployment_ref:
        required: true
        type: string
    secrets:
      PROD_USERNAME:
        required: true
      PROD_PASSWORD:
        required: true
      SLACK_BOT_TOKEN:
        required: true
      SLACK_RELEASE_CHANNEL_ID:
        required: true
      SLACK_ALERTS_INTEGRATIONS_CHANNEL_ID:
        required: true

permissions:
  contents: read

jobs:
  extract-version:
    name: Extract Deployment Version
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.extract-version.outputs.version }}
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@e14015d583714f6e62063499dc959a02595150a1 # v2.21.1
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          ref: ${{ inputs.deployment_ref }}
          fetch-depth: 1

      - name: Extract Package Version
        id: extract-version
        run: |
          version=$(jq -r .version package.json)
          echo "$version"
          echo "version=$version" >> "$GITHUB_OUTPUT"

  deploy:
    needs: [extract-version]
    name: Deployment To Production DB
    uses: ./.github/workflows/deploy.yml
    with:
      environment: production
      deploy_url: https://api.rudderstack.com
      notify: true
      version: ${{ needs.extract-version.outputs.version }}
      ref: ${{ inputs.deployment_ref }}
    secrets:
      API_USERNAME: ${{ secrets.PROD_USERNAME }}
      API_PASSWORD: ${{ secrets.PROD_PASSWORD }}
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      SLACK_RELEASE_CHANNEL_ID: ${{ secrets.SLACK_RELEASE_CHANNEL_ID }}
      SLACK_ALERTS_INTEGRATIONS_CHANNEL_ID: ${{ secrets.SLACK_ALERTS_INTEGRATIONS_CHANNEL_ID }}
