name: Deploy Configurations To Staging DB

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    branches:
      - main

jobs:
  deploy:
    name: Deployment To Staging DB
    # Only pull requests from release candidate branches must trigger
    if: (startsWith(github.event.pull_request.head.ref, 'release/') || startsWith(github.event.pull_request.head.ref, 'hotfix-release/'))
    uses: ./.github/workflows/deploy.yml
    with:
      deploy_url: https://api.staging.rudderlabs.com
      ref: ${{ github.event.pull_request.head.ref }}
    secrets:
      API_USERNAME: ${{ secrets.STAGING_USERNAME }}
      API_PASSWORD: ${{ secrets.STAGING_PASSWORD }}
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      SLACK_RELEASE_CHANNEL_ID: ${{ secrets.SLACK_RELEASE_CHANNEL_ID }}

  trigger-post-deployment-tests:
    name: Trigger Post Deployment Tests
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: Trigger Post Deployment Tests
        uses: peter-evans/repository-dispatch@ff45666b9427631e3450c54a1bcbee4d9ff4d7c0 # v3.0.0
        with:
          token: ${{ secrets.PAT }}
          repository: rudderlabs/rudder-client-side-test
          event-type: post-deployment-integration-tests
          client-payload: |-
            {
              "environment": "staging",
              "ref": "${{ github.event.pull_request.head.ref }}",
              "tags": "@integrations-config and @staging"
            }
