name: Deploy config to DB

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current develop
        uses: actions/checkout@v3
        with:
          ref: develop
      - name: Install python
        uses: actions/setup-python@v4
        with:
            python-version: '3.9.13'
      - name: Setup Python
        run: python -m pip install --upgrade pip requests jsondiff
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      - name: Display current location files
        run: |
         echo current directory
         ls -a
         pwd
         which python
      - name: Execute script
        env:
          API_USER: ${{secrets.DEV_USERNAME}}
          API_PASSWORD: ${{secrets.DEV_PASSWORD}}
        run: |
         python scripts/action.py ${{secrets.DEV_CONTROL_PLANE_URL}}
      - name: npm install
        uses: actions/setup-node@v2
        with:
          node-version: 16
        run: npm install
      - name: Jest
        run: npm run test
