name: Deploy config to DB

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout current master
      uses: actions/checkout@master
    - name: Install python
      uses: actions/setup-python@v2
    - name: Setup Python
      run: chmod +x scripts/setup-python.sh;./scripts/setup-python.sh
    - name: Execute script
      run: python3 scripts/action.py ${{secrets.DEV_CONTROL_PLANE_URL}} ${{secrets.DEV_USERNAME}} ${{secrets.DEV_PASSWORD}}
    - name: Update status
      run: echo "Success"
