name: Deploy config to DB

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current develop
        uses: actions/checkout@v3
        with:
          ref: develop
      - name: Set Node 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm run test
      - name: Install python
        uses: actions/setup-python@v4
        with:
            python-version: '3.9.13'
      - name: Setup Python
        run: python -m pip install --upgrade pip requests jsondiff
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      - name: Display current location files
        run: |
         echo current directory
         ls -a
         pwd
         which python
      - name: Display current Version of Config-Schema
        run: echo $(head -1 .version)
      - name: Execute script
        env:
          API_USER: ${{secrets.DEV_USERNAME}}
          API_PASSWORD: ${{secrets.DEV_PASSWORD}}
        run: |
         python scripts/action.py https://api.dev.rudderlabs.com
         python scripts/action.py https://api.staging.rudderlabs.com
