name: Deploy config to DB

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current master
        uses: actions/checkout@v3
      - name: Install python
        uses: actions/setup-python@v4
        with:
            python-version: '3.x'
      - name: Setup Python
        run: python -m pip install --upgrade pip requests jsondiff
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      - name: Execute script
        run: |
         python scripts/action.py ${{secrets.PROD_CONTROL_PLANE_URL}} ${{secrets.PROD_USERNAME}} ${{secrets.PROD_PASSWORD}}
