# https://github.com/marketplace/actions/jest-coverage-report
name: 'Coverage'
on:
  pull_request:
    branches:
      - "*"

jobs:
  coverage:
    name: 'Coverage'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Coverage report
        uses: ArtiomTr/jest-coverage-report-action@v2
