export const DYNAMIC_CONFIG_FIELDS: Record<string, string[]> = {
  ZENDESK: ['email', 'sourceName', 'domain'],
  ZAPIER: ['trackEventsToZap', 'pageScreenEventsToZap'],
  WEBHOOK: ['headers', 'webhookUrl'],
  SENDGRID: ['listId'],
  SEGMENT: ['writeKey'],
  SALESFORCE: ['userName'],
  REDDIT: ['accountId'],
  MP: ['serviceAccountSecret', 'apiSecret', 'projectId', 'serviceAccountUserName'],
  MOVABLE_INK: ['endpoint'],
  MAILCHIMP: ['apiKey', 'datacenterId', 'audienceId'],
  KLAVIYO: ['listId', 'publicApiKey'],
  INTERCOM: ['apiKey', 'appId'],
  IMPACT: ['campaignId', 'accountSID', 'eventTypeId'],
  HS: ['hubID', 'hubspotEvents', 'accessToken'],
  GTM: ['containerID'],
  GA: ['metrics', 'trackingID'],
  BRAZE: ['appKey'],
  BQSTREAM: ['tableId'],
  AM: ['groupTypeTrait', 'groupValueTrait'],
  AF: ['appleAppId', 'androidAppId'],
  ADOBE_ANALYTICS: ['trackingServerUrl', 'reportSuiteIds', 'trackingServerSecureUrl'],
  FACEBOOK_PIXEL: ['legacyConversionPixelId', 'pixelId', 'accessToken'],
  FACEBOOK_CONVERSIONS: ['datasetId'],
  FACEBOOK_OFFLINE_CONVERSIONS: ['eventsToIds'],
  FB_CUSTOM_AUDIENCE: ['audienceId'],
  GA4: ['measurementId'],
  GOOGLE_ADWORDS_ENHANCED_CONVERSIONS: ['loginCustomerId', 'customerId'],
  GOOGLE_ADWORDS_OFFLINE_CONVERSIONS: ['loginCustomerId', 'customerId'],
  GOOGLEADS: ['conversionID'],
  SNAPCHAT_CONVERSION: ['pixelId'],
  PINTEREST_TAG: ['advertiserId'],
};
